-- Aplica el esquema completo de forma atómica sobre una base vacía.
BEGIN;

-- Controla qué estructura puede editarse durante cada etapa de configuración.
CREATE TYPE scheme_status AS ENUM (
  'DRAFT',
  'LEVELS_DEFINED',
  'LOCATIONS_DEFINED',
  'PARTIALLY_ASSIGNED',
  'ASSIGNED'
);

-- Clasifica la perspectiva visual de cada capa de mapa.
CREATE TYPE map_layer_type AS ENUM (
  'TOP',
  'FRONT',
  'OTHER'
);

-- Distingue SVG concretos de plantillas reutilizables con slots.
CREATE TYPE map_render_mode AS ENUM (
  'STATIC',
  'TEMPLATE'
);

-- Conserva cuentas de acceso y referencias básicas de auditoría.
CREATE TABLE users (
  user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR(60) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  full_name      VARCHAR(120) NOT NULL,
  enabled        BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at  TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT users_username_not_blank CHECK (btrim(username) <> ''),
  CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
  CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
  CONSTRAINT users_full_name_not_blank CHECK (btrim(full_name) <> '')
);

-- Evita nombres de usuario duplicados sin distinguir mayúsculas.
CREATE UNIQUE INDEX users_username_unique_idx ON users (lower(username));
-- Evita correos duplicados sin distinguir mayúsculas.
CREATE UNIQUE INDEX users_email_unique_idx ON users (lower(email));

-- Versiona el contrato completo de ordenamiento usado por cada esquema.
CREATE TABLE ordering_profiles (
  ordering_profile_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    VARCHAR(80) NOT NULL,
  description             TEXT,
  ordering_spec_version   VARCHAR(20) NOT NULL,
  normalization_profile   VARCHAR(40) NOT NULL,
  comparable_key_version  SMALLINT NOT NULL,
  enabled                 BOOLEAN NOT NULL DEFAULT true,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ordering_profiles_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT ordering_profiles_spec_not_blank CHECK (btrim(ordering_spec_version) <> ''),
  CONSTRAINT ordering_profiles_normalization_not_blank CHECK (btrim(normalization_profile) <> ''),
  CONSTRAINT ordering_profiles_key_version_positive CHECK (comparable_key_version > 0),
  CONSTRAINT ordering_profiles_contract_unique UNIQUE (
    ordering_spec_version,
    normalization_profile,
    comparable_key_version
  )
);

-- Evita nombres de perfil duplicados sin distinguir mayúsculas.
CREATE UNIQUE INDEX ordering_profiles_name_unique_idx
  ON ordering_profiles (lower(name));

-- Agrupa niveles, ubicaciones, rangos y mapas bajo una configuración publicable.
CREATE TABLE schemes (
  scheme_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 VARCHAR(80) NOT NULL,
  status               scheme_status NOT NULL DEFAULT 'DRAFT',
  short_description    VARCHAR(255),
  is_active            BOOLEAN NOT NULL DEFAULT false,
  enabled              BOOLEAN NOT NULL DEFAULT true,
  ordering_profile_id  INTEGER NOT NULL,
  created_by           INTEGER,
  published_by         INTEGER,
  published_at         TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT schemes_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT schemes_active_valid CHECK (
    NOT is_active OR (enabled AND status = 'ASSIGNED')
  ),
  CONSTRAINT schemes_publication_metadata_complete CHECK (
    (published_by IS NULL AND published_at IS NULL)
    OR (
      published_by IS NOT NULL
      AND published_at IS NOT NULL
      AND status = 'ASSIGNED'
    )
  ),
  CONSTRAINT schemes_ordering_profile_fkey
    FOREIGN KEY (ordering_profile_id)
    REFERENCES ordering_profiles (ordering_profile_id),
  CONSTRAINT schemes_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),
  CONSTRAINT schemes_published_by_fkey
    FOREIGN KEY (published_by)
    REFERENCES users (user_id)
);

-- Evita nombres de esquema duplicados sin distinguir mayúsculas.
CREATE UNIQUE INDEX schemes_name_unique_idx ON schemes (lower(name));
-- Garantiza que exista como máximo un esquema activo.
CREATE UNIQUE INDEX schemes_one_active_idx ON schemes (is_active) WHERE is_active;
-- Acelera la consulta de esquemas por contrato de ordenamiento.
CREATE INDEX schemes_ordering_profile_idx ON schemes (ordering_profile_id);
-- Acelera consultas de auditoría por usuario creador.
CREATE INDEX schemes_created_by_idx ON schemes (created_by) WHERE created_by IS NOT NULL;
-- Acelera consultas de auditoría por usuario publicador.
CREATE INDEX schemes_published_by_idx ON schemes (published_by) WHERE published_by IS NOT NULL;

-- Define el árbol de tipos de ubicación permitido para un esquema.
CREATE TABLE scheme_levels (
  scheme_level_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id          INTEGER NOT NULL,
  parent_level_id    INTEGER,
  name               VARCHAR(60) NOT NULL,
  sort_order         SMALLINT NOT NULL DEFAULT 0,
  is_search_terminal BOOLEAN NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT scheme_levels_scheme_level_unique
    UNIQUE (scheme_id, scheme_level_id),
  CONSTRAINT scheme_levels_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT scheme_levels_sort_nonnegative CHECK (sort_order >= 0),
  CONSTRAINT scheme_levels_not_self_parent CHECK (
    parent_level_id IS NULL OR parent_level_id <> scheme_level_id
  ),
  CONSTRAINT scheme_levels_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id),
  CONSTRAINT scheme_levels_parent_same_scheme_fkey
    FOREIGN KEY (scheme_id, parent_level_id)
    REFERENCES scheme_levels (scheme_id, scheme_level_id)
    DEFERRABLE INITIALLY IMMEDIATE
);

-- Permite como máximo un nivel raíz por esquema.
CREATE UNIQUE INDEX scheme_levels_one_root_idx
  ON scheme_levels (scheme_id)
  WHERE parent_level_id IS NULL;

-- Evita nombres repetidos entre niveles hermanos.
CREATE UNIQUE INDEX scheme_levels_sibling_name_unique_idx
  ON scheme_levels (scheme_id, parent_level_id, lower(name))
  WHERE parent_level_id IS NOT NULL;

-- Evita posiciones repetidas entre niveles hermanos.
CREATE UNIQUE INDEX scheme_levels_sibling_order_unique_idx
  ON scheme_levels (scheme_id, parent_level_id, sort_order)
  WHERE parent_level_id IS NOT NULL;

-- Soporta recorridos ordenados del árbol de niveles.
CREATE INDEX scheme_levels_parent_idx
  ON scheme_levels (scheme_id, parent_level_id, sort_order);

-- Materializa ubicaciones físicas y guarda los rangos usados por la búsqueda.
CREATE TABLE locations (
  location_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id               INTEGER NOT NULL,
  parent_location_id      INTEGER,
  scheme_level_id         INTEGER NOT NULL,
  name                    VARCHAR(70) NOT NULL,
  code                    VARCHAR(120) NOT NULL,
  sort_order              SMALLINT NOT NULL DEFAULT 0,
  range_start_raw         VARCHAR(120),
  range_end_raw           VARCHAR(120),
  range_start_normalized  JSONB,
  range_end_normalized    JSONB,
  range_start_key         BYTEA,
  range_end_key           BYTEA,
  created_by              INTEGER,
  updated_by              INTEGER,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT locations_scheme_location_unique
    UNIQUE (scheme_id, location_id),
  CONSTRAINT locations_scheme_code_unique
    UNIQUE (scheme_id, code),
  CONSTRAINT locations_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT locations_code_not_blank CHECK (btrim(code) <> ''),
  CONSTRAINT locations_sort_nonnegative CHECK (sort_order >= 0),
  CONSTRAINT locations_not_self_parent CHECK (
    parent_location_id IS NULL OR parent_location_id <> location_id
  ),
  CONSTRAINT locations_normalized_objects CHECK (
    (range_start_normalized IS NULL OR jsonb_typeof(range_start_normalized) = 'object')
    AND
    (range_end_normalized IS NULL OR jsonb_typeof(range_end_normalized) = 'object')
  ),
  CONSTRAINT locations_range_complete CHECK (
    (
      range_start_raw IS NULL
      AND range_end_raw IS NULL
      AND range_start_normalized IS NULL
      AND range_end_normalized IS NULL
      AND range_start_key IS NULL
      AND range_end_key IS NULL
    )
    OR
    (
      range_start_raw IS NOT NULL
      AND range_end_raw IS NOT NULL
      AND range_start_normalized IS NOT NULL
      AND range_end_normalized IS NOT NULL
      AND range_start_key IS NOT NULL
      AND range_end_key IS NOT NULL
      AND range_start_key <= range_end_key
    )
  ),
  CONSTRAINT locations_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id),
  CONSTRAINT locations_level_same_scheme_fkey
    FOREIGN KEY (scheme_id, scheme_level_id)
    REFERENCES scheme_levels (scheme_id, scheme_level_id)
    DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT locations_parent_same_scheme_fkey
    FOREIGN KEY (scheme_id, parent_location_id)
    REFERENCES locations (scheme_id, location_id)
    DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT locations_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),
  CONSTRAINT locations_updated_by_fkey
    FOREIGN KEY (updated_by)
    REFERENCES users (user_id)
);

-- Permite como máximo una ubicación raíz por esquema.
CREATE UNIQUE INDEX locations_one_root_idx
  ON locations (scheme_id)
  WHERE parent_location_id IS NULL;

-- Evita posiciones repetidas entre ubicaciones hermanas.
CREATE UNIQUE INDEX locations_sibling_order_unique_idx
  ON locations (scheme_id, parent_location_id, sort_order)
  WHERE parent_location_id IS NOT NULL;

-- Soporta recorridos ordenados del árbol de ubicaciones.
CREATE INDEX locations_parent_order_idx
  ON locations (scheme_id, parent_location_id, sort_order, location_id);

-- Agrupa ubicaciones por el nivel que materializan.
CREATE INDEX locations_level_idx
  ON locations (scheme_id, scheme_level_id);

-- Acelera consultas de auditoría por usuario creador.
CREATE INDEX locations_created_by_idx
  ON locations (created_by)
  WHERE created_by IS NOT NULL;

-- Acelera consultas de auditoría por último usuario editor.
CREATE INDEX locations_updated_by_idx
  ON locations (updated_by)
  WHERE updated_by IS NOT NULL;

-- Reduce el conjunto candidato en búsquedas de una clave dentro de un rango.
CREATE INDEX locations_range_lookup_idx
  ON locations (scheme_id, range_start_key, range_end_key)
  WHERE range_start_key IS NOT NULL;

-- Define una vista lógica que puede representarse con uno o más SVG.
CREATE TABLE map_layers (
  map_layer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id     INTEGER NOT NULL,
  name          VARCHAR(120) NOT NULL,
  view_type     map_layer_type NOT NULL,
  render_mode   map_render_mode NOT NULL,
  enabled       BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT map_layers_scheme_layer_unique
    UNIQUE (scheme_id, map_layer_id),
  CONSTRAINT map_layers_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT map_layers_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id)
);

-- Evita nombres de capa duplicados dentro del mismo esquema.
CREATE UNIQUE INDEX map_layers_scheme_name_unique_idx
  ON map_layers (scheme_id, lower(name));

-- Permite buscar capas habilitadas por esquema y perspectiva.
CREATE INDEX map_layers_scheme_type_idx
  ON map_layers (scheme_id, view_type, enabled);

-- Declara qué niveles representa una capa y su posible destino de drilldown.
CREATE TABLE map_layer_scheme_levels (
  map_layer_id           INTEGER NOT NULL,
  scheme_level_id        INTEGER NOT NULL,
  drilldown_map_layer_id INTEGER,

  PRIMARY KEY (map_layer_id, scheme_level_id),

  CONSTRAINT map_layer_scheme_levels_no_self_drilldown CHECK (
    drilldown_map_layer_id IS NULL
    OR drilldown_map_layer_id <> map_layer_id
  ),
  CONSTRAINT map_layer_scheme_levels_layer_fkey
    FOREIGN KEY (map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE CASCADE,
  CONSTRAINT map_layer_scheme_levels_level_fkey
    FOREIGN KEY (scheme_level_id)
    REFERENCES scheme_levels (scheme_level_id),
  CONSTRAINT map_layer_scheme_levels_drilldown_fkey
    FOREIGN KEY (drilldown_map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE SET NULL
);

-- Permite localizar las capas que representan un nivel.
CREATE INDEX map_layer_scheme_levels_level_idx
  ON map_layer_scheme_levels (scheme_level_id, map_layer_id);

-- Permite localizar referencias entrantes a una capa de drilldown.
CREATE INDEX map_layer_scheme_levels_drilldown_idx
  ON map_layer_scheme_levels (drilldown_map_layer_id)
  WHERE drilldown_map_layer_id IS NOT NULL;

-- Registra los archivos SVG concretos o las variantes de plantilla de una capa.
CREATE TABLE map_layer_svgs (
  map_layer_svg_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_layer_id     INTEGER NOT NULL,
  name             VARCHAR(120) NOT NULL,
  variant_code     VARCHAR(60),
  asset_url        TEXT NOT NULL,
  slot_count       SMALLINT,
  enabled          BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT map_layer_svgs_layer_svg_unique
    UNIQUE (map_layer_id, map_layer_svg_id),
  CONSTRAINT map_layer_svgs_variant_unique
    UNIQUE (map_layer_id, variant_code),
  CONSTRAINT map_layer_svgs_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT map_layer_svgs_url_not_blank CHECK (btrim(asset_url) <> ''),
  CONSTRAINT map_layer_svgs_variant_not_blank CHECK (
    variant_code IS NULL OR btrim(variant_code) <> ''
  ),
  CONSTRAINT map_layer_svgs_slot_count_positive CHECK (
    slot_count IS NULL OR slot_count > 0
  ),
  CONSTRAINT map_layer_svgs_layer_fkey
    FOREIGN KEY (map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE CASCADE
);

-- Selecciona una variante de plantilla para cada ubicación contextual.
CREATE TABLE map_layer_svg_assignments (
  map_layer_id       INTEGER NOT NULL,
  map_layer_svg_id   INTEGER NOT NULL,
  context_location_id INTEGER NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (map_layer_id, context_location_id),

  CONSTRAINT map_layer_svg_assignments_svg_fkey
    FOREIGN KEY (map_layer_id, map_layer_svg_id)
    REFERENCES map_layer_svgs (map_layer_id, map_layer_svg_id)
    ON DELETE CASCADE,
  CONSTRAINT map_layer_svg_assignments_location_fkey
    FOREIGN KEY (context_location_id)
    REFERENCES locations (location_id)
    ON DELETE CASCADE
);

-- Permite proponer plantillas habilitadas con la cantidad de slots requerida.
CREATE INDEX map_layer_svgs_slot_lookup_idx
  ON map_layer_svgs (map_layer_id, slot_count)
  WHERE enabled AND slot_count IS NOT NULL;

-- Permite localizar todas las asignaciones que usan un SVG.
CREATE INDEX map_layer_svg_assignments_svg_idx
  ON map_layer_svg_assignments (map_layer_svg_id);

-- Permite abrir las plantillas asignadas a una ubicación contextual.
CREATE INDEX map_layer_svg_assignments_location_idx
  ON map_layer_svg_assignments (context_location_id);

-- Centraliza la actualización automática de columnas updated_at.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- Mantiene users.updated_at después de cada modificación.
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mantiene schemes.updated_at después de cada modificación.
CREATE TRIGGER schemes_set_updated_at
BEFORE UPDATE ON schemes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mantiene scheme_levels.updated_at después de cada modificación.
CREATE TRIGGER scheme_levels_set_updated_at
BEFORE UPDATE ON scheme_levels
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mantiene locations.updated_at después de cada modificación.
CREATE TRIGGER locations_set_updated_at
BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mantiene map_layers.updated_at después de cada modificación.
CREATE TRIGGER map_layers_set_updated_at
BEFORE UPDATE ON map_layers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mantiene map_layer_svgs.updated_at después de cada modificación.
CREATE TRIGGER map_layer_svgs_set_updated_at
BEFORE UPDATE ON map_layer_svgs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Rechaza ciclos, relaciones entre esquemas y más de un terminal por rama.
CREATE OR REPLACE FUNCTION validate_scheme_level_tree()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  ancestor_has_terminal   BOOLEAN := false;
  descendant_has_terminal BOOLEAN := false;
BEGIN
  IF TG_OP = 'UPDATE'
     AND NEW.scheme_id IS DISTINCT FROM OLD.scheme_id
     AND EXISTS (
       SELECT 1
       FROM map_layer_scheme_levels AS mlsl
       JOIN map_layers AS ml
         ON ml.map_layer_id = mlsl.map_layer_id
       WHERE mlsl.scheme_level_id = NEW.scheme_level_id
         AND ml.scheme_id <> NEW.scheme_id
     )
  THEN
    RAISE EXCEPTION 'El nivel está asociado con un MapLayer de otro esquema';
  END IF;

  IF TG_OP = 'UPDATE'
     AND (
       NEW.scheme_id IS DISTINCT FROM OLD.scheme_id
       OR NEW.parent_level_id IS DISTINCT FROM OLD.parent_level_id
     )
     AND EXISTS (
       SELECT 1
       FROM map_layer_scheme_levels AS mlsl
       JOIN map_layer_svg_assignments AS a
         ON a.map_layer_id = mlsl.map_layer_id
       WHERE mlsl.scheme_level_id = NEW.scheme_level_id
     )
  THEN
    RAISE EXCEPTION 'Debe eliminar las asignaciones SVG antes de mover el nivel';
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.parent_level_id IS NOT NULL AND EXISTS (
    WITH RECURSIVE descendants AS (
      SELECT sl.scheme_level_id
      FROM scheme_levels AS sl
      WHERE sl.scheme_id = NEW.scheme_id
        AND sl.parent_level_id = NEW.scheme_level_id
      UNION ALL
      SELECT child.scheme_level_id
      FROM scheme_levels AS child
      JOIN descendants AS parent
        ON child.parent_level_id = parent.scheme_level_id
      WHERE child.scheme_id = NEW.scheme_id
    )
    SELECT 1
    FROM descendants
    WHERE scheme_level_id = NEW.parent_level_id
  ) THEN
    RAISE EXCEPTION 'La relación propuesta produciría un ciclo de niveles';
  END IF;

  IF NEW.parent_level_id IS NOT NULL THEN
    WITH RECURSIVE ancestors AS (
      SELECT sl.scheme_level_id, sl.parent_level_id, sl.is_search_terminal
      FROM scheme_levels AS sl
      WHERE sl.scheme_id = NEW.scheme_id
        AND sl.scheme_level_id = NEW.parent_level_id
      UNION ALL
      SELECT parent.scheme_level_id,
             parent.parent_level_id,
             parent.is_search_terminal
      FROM scheme_levels AS parent
      JOIN ancestors AS child
        ON parent.scheme_level_id = child.parent_level_id
      WHERE parent.scheme_id = NEW.scheme_id
    )
    SELECT EXISTS (
      SELECT 1 FROM ancestors WHERE is_search_terminal
    ) INTO ancestor_has_terminal;
  END IF;

  WITH RECURSIVE descendants AS (
    SELECT sl.scheme_level_id, sl.is_search_terminal
    FROM scheme_levels AS sl
    WHERE sl.scheme_id = NEW.scheme_id
      AND sl.parent_level_id = NEW.scheme_level_id
    UNION ALL
    SELECT child.scheme_level_id, child.is_search_terminal
    FROM scheme_levels AS child
    JOIN descendants AS parent
      ON child.parent_level_id = parent.scheme_level_id
    WHERE child.scheme_id = NEW.scheme_id
  )
  SELECT EXISTS (
    SELECT 1 FROM descendants WHERE is_search_terminal
  ) INTO descendant_has_terminal;

  IF NEW.is_search_terminal AND descendant_has_terminal THEN
    RAISE EXCEPTION 'Un terminal de búsqueda no puede tener otro terminal descendiente';
  END IF;

  IF ancestor_has_terminal AND (NEW.is_search_terminal OR descendant_has_terminal) THEN
    RAISE EXCEPTION 'Una rama no puede contener dos terminales de búsqueda';
  END IF;

  RETURN NEW;
END;
$$;

-- Limita los cambios de scheme_levels a esquemas en DRAFT.
CREATE OR REPLACE FUNCTION ensure_scheme_levels_are_draft()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_scheme_id INTEGER;
  affected_status    scheme_status;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.scheme_id IS DISTINCT FROM NEW.scheme_id AND EXISTS (
    SELECT 1
    FROM schemes
    WHERE scheme_id IN (OLD.scheme_id, NEW.scheme_id)
      AND status <> 'DRAFT'
  ) THEN
    RAISE EXCEPTION 'Los niveles solo pueden moverse entre esquemas en estado DRAFT';
  END IF;

  affected_scheme_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.scheme_id ELSE NEW.scheme_id END;

  SELECT status
  INTO affected_status
  FROM schemes
  WHERE scheme_id = affected_scheme_id;

  IF affected_status <> 'DRAFT' THEN
    RAISE EXCEPTION 'Los niveles solo pueden modificarse cuando el esquema está en DRAFT';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

-- Aplica la restricción de etapa a toda escritura de niveles.
CREATE TRIGGER scheme_levels_require_draft
BEFORE INSERT OR UPDATE OR DELETE
ON scheme_levels
FOR EACH ROW EXECUTE FUNCTION ensure_scheme_levels_are_draft();

-- Valida la topología cuando cambia el padre, esquema o terminal del nivel.
CREATE TRIGGER scheme_levels_validate_tree
BEFORE INSERT OR UPDATE OF scheme_id, parent_level_id, is_search_terminal
ON scheme_levels
FOR EACH ROW EXECUTE FUNCTION validate_scheme_level_tree();

-- Comprueba una raíz única y exactamente un terminal en cada rama raíz-hoja.
CREATE OR REPLACE FUNCTION assert_scheme_search_coverage(p_scheme_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  IF (
    SELECT count(*)
    FROM scheme_levels
    WHERE scheme_id = p_scheme_id
      AND parent_level_id IS NULL
  ) <> 1 THEN
    RAISE EXCEPTION 'El esquema debe tener exactamente un nivel raíz';
  END IF;

  IF EXISTS (
    WITH RECURSIVE walk AS (
      SELECT sl.scheme_level_id,
             CASE WHEN sl.is_search_terminal THEN 1 ELSE 0 END AS terminal_count
      FROM scheme_levels AS sl
      WHERE sl.scheme_id = p_scheme_id
        AND sl.parent_level_id IS NULL
      UNION ALL
      SELECT child.scheme_level_id,
             parent.terminal_count
               + CASE WHEN child.is_search_terminal THEN 1 ELSE 0 END
      FROM scheme_levels AS child
      JOIN walk AS parent
        ON child.parent_level_id = parent.scheme_level_id
      WHERE child.scheme_id = p_scheme_id
    )
    SELECT 1
    FROM walk AS node
    WHERE NOT EXISTS (
      SELECT 1
      FROM scheme_levels AS child
      WHERE child.scheme_id = p_scheme_id
        AND child.parent_level_id = node.scheme_level_id
    )
      AND node.terminal_count <> 1
  ) THEN
    RAISE EXCEPTION 'Cada rama raíz-hoja debe contener exactamente un terminal de búsqueda';
  END IF;
END;
$$;

-- Valida la jerarquía de locations y restringe rangos a terminales y etapas válidas.
CREATE OR REPLACE FUNCTION validate_location_tree_and_range()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  expected_parent_level_id INTEGER;
  actual_parent_level_id   INTEGER;
  level_is_terminal        BOOLEAN;
  scheme_stage             scheme_status;
BEGIN
  SELECT sl.parent_level_id, sl.is_search_terminal
  INTO expected_parent_level_id, level_is_terminal
  FROM scheme_levels AS sl
  WHERE sl.scheme_id = NEW.scheme_id
    AND sl.scheme_level_id = NEW.scheme_level_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El nivel de la ubicación no existe en el esquema';
  END IF;

  IF NEW.parent_location_id IS NULL THEN
    IF expected_parent_level_id IS NOT NULL THEN
      RAISE EXCEPTION 'Una ubicación raíz debe usar el nivel raíz';
    END IF;
  ELSE
    SELECT parent.scheme_level_id
    INTO actual_parent_level_id
    FROM locations AS parent
    WHERE parent.scheme_id = NEW.scheme_id
      AND parent.location_id = NEW.parent_location_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'La ubicación padre no existe en el mismo esquema';
    END IF;

    IF actual_parent_level_id IS DISTINCT FROM expected_parent_level_id THEN
      RAISE EXCEPTION 'El nivel de la ubicación hija no corresponde al nivel de su padre';
    END IF;
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.parent_location_id IS NOT NULL AND EXISTS (
    WITH RECURSIVE descendants AS (
      SELECT l.location_id
      FROM locations AS l
      WHERE l.scheme_id = NEW.scheme_id
        AND l.parent_location_id = NEW.location_id
      UNION ALL
      SELECT child.location_id
      FROM locations AS child
      JOIN descendants AS parent
        ON child.parent_location_id = parent.location_id
      WHERE child.scheme_id = NEW.scheme_id
    )
    SELECT 1
    FROM descendants
    WHERE location_id = NEW.parent_location_id
  ) THEN
    RAISE EXCEPTION 'La relación propuesta produciría un ciclo de ubicaciones';
  END IF;

  IF NEW.range_start_key IS NOT NULL AND NOT level_is_terminal THEN
    RAISE EXCEPTION 'Solo una ubicación terminal de búsqueda puede contener un rango';
  END IF;

  SELECT status
  INTO scheme_stage
  FROM schemes
  WHERE scheme_id = NEW.scheme_id;

  IF NEW.range_start_key IS NOT NULL
     AND scheme_stage NOT IN ('PARTIALLY_ASSIGNED', 'ASSIGNED')
  THEN
    RAISE EXCEPTION 'Los rangos solo pueden asignarse desde PARTIALLY_ASSIGNED';
  END IF;

  IF NEW.range_start_key IS NULL AND scheme_stage = 'ASSIGNED' THEN
    RAISE EXCEPTION 'No se puede retirar un rango mientras el esquema está ASSIGNED';
  END IF;

  RETURN NEW;
END;
$$;

-- Limita los cambios estructurales de locations a LEVELS_DEFINED.
CREATE OR REPLACE FUNCTION ensure_location_structure_editable()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_scheme_id INTEGER;
  affected_status    scheme_status;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.scheme_id IS DISTINCT FROM NEW.scheme_id AND EXISTS (
    SELECT 1
    FROM schemes
    WHERE scheme_id IN (OLD.scheme_id, NEW.scheme_id)
      AND status <> 'LEVELS_DEFINED'
  ) THEN
    RAISE EXCEPTION 'Las locations solo pueden moverse entre esquemas en estado LEVELS_DEFINED';
  END IF;

  affected_scheme_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.scheme_id ELSE NEW.scheme_id END;

  SELECT status
  INTO affected_status
  FROM schemes
  WHERE scheme_id = affected_scheme_id;

  IF affected_status <> 'LEVELS_DEFINED' THEN
    RAISE EXCEPTION 'La estructura de locations solo puede modificarse en estado LEVELS_DEFINED';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

-- Restringe la creación y eliminación de locations a la etapa estructural.
CREATE TRIGGER locations_require_defined_insert_delete
BEFORE INSERT OR DELETE
ON locations
FOR EACH ROW EXECUTE FUNCTION ensure_location_structure_editable();

-- Restringe a LEVELS_DEFINED las columnas que cambian la estructura física.
CREATE TRIGGER locations_require_defined_update
BEFORE UPDATE OF
  scheme_id,
  parent_location_id,
  scheme_level_id,
  name,
  code,
  sort_order
ON locations
FOR EACH ROW EXECUTE FUNCTION ensure_location_structure_editable();

-- Revalida jerarquía y rango cuando cambia cualquiera de sus campos fuente.
CREATE TRIGGER locations_validate_tree_and_range
BEFORE INSERT OR UPDATE OF
  scheme_id,
  parent_location_id,
  scheme_level_id,
  range_start_raw,
  range_end_raw,
  range_start_normalized,
  range_end_normalized,
  range_start_key,
  range_end_key
ON locations
FOR EACH ROW EXECUTE FUNCTION validate_location_tree_and_range();

-- Exige una raíz y la materialización de todos los niveles hijos esperados.
CREATE OR REPLACE FUNCTION assert_scheme_locations_defined(p_scheme_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  IF (
    SELECT count(*)
    FROM locations
    WHERE scheme_id = p_scheme_id
      AND parent_location_id IS NULL
  ) <> 1 THEN
    RAISE EXCEPTION 'El esquema debe tener exactamente una location raíz';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM locations AS parent
    JOIN scheme_levels AS expected_child_level
      ON expected_child_level.scheme_id = parent.scheme_id
     AND expected_child_level.parent_level_id = parent.scheme_level_id
    WHERE parent.scheme_id = p_scheme_id
      AND NOT EXISTS (
        SELECT 1
        FROM locations AS child
        WHERE child.scheme_id = parent.scheme_id
          AND child.parent_location_id = parent.location_id
          AND child.scheme_level_id = expected_child_level.scheme_level_id
      )
  ) THEN
    RAISE EXCEPTION 'Cada location debe materializar todos los niveles hijos definidos para su nivel';
  END IF;
END;
$$;

-- Controla transiciones de scheme_status y valida cada etapa antes de aceptarla.
CREATE OR REPLACE FUNCTION validate_scheme_state()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'DRAFT' THEN
      RAISE EXCEPTION 'Un esquema nuevo debe iniciar en DRAFT';
    END IF;

    RETURN NEW;
  END IF;

  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NEW;
  END IF;

  IF NOT (
    (OLD.status = 'DRAFT' AND NEW.status = 'LEVELS_DEFINED')
    OR (OLD.status = 'LEVELS_DEFINED' AND NEW.status IN ('DRAFT', 'LOCATIONS_DEFINED'))
    OR (OLD.status = 'LOCATIONS_DEFINED' AND NEW.status IN ('LEVELS_DEFINED', 'PARTIALLY_ASSIGNED'))
    OR (OLD.status = 'PARTIALLY_ASSIGNED' AND NEW.status IN ('LOCATIONS_DEFINED', 'ASSIGNED'))
    OR (OLD.status = 'ASSIGNED' AND NEW.status = 'PARTIALLY_ASSIGNED')
  ) THEN
    RAISE EXCEPTION 'Transición de estado no permitida: % -> %', OLD.status, NEW.status;
  END IF;

  IF NEW.status <> 'DRAFT' THEN
    PERFORM assert_scheme_search_coverage(NEW.scheme_id);
  END IF;

  IF NEW.status = 'DRAFT' AND (
    EXISTS (
      SELECT 1 FROM locations WHERE scheme_id = NEW.scheme_id
    )
    OR EXISTS (
      SELECT 1 FROM map_layers WHERE scheme_id = NEW.scheme_id
    )
  ) THEN
    RAISE EXCEPTION 'Un esquema con locations o MapLayers no puede volver a DRAFT';
  END IF;

  IF NEW.status = 'LEVELS_DEFINED' AND (
    EXISTS (
      SELECT 1
      FROM locations
      WHERE scheme_id = NEW.scheme_id
        AND range_start_key IS NOT NULL
    )
    OR EXISTS (
      SELECT 1 FROM map_layers WHERE scheme_id = NEW.scheme_id
    )
  ) THEN
    RAISE EXCEPTION 'Para volver a LEVELS_DEFINED deben eliminarse primero rangos y MapLayers';
  END IF;

  IF NEW.status = 'LOCATIONS_DEFINED' AND EXISTS (
    SELECT 1
    FROM locations
    WHERE scheme_id = NEW.scheme_id
      AND range_start_key IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'LOCATIONS_DEFINED no puede conservar rangos asignados';
  END IF;

  IF NEW.status IN ('LOCATIONS_DEFINED', 'PARTIALLY_ASSIGNED', 'ASSIGNED') THEN
    PERFORM assert_scheme_locations_defined(NEW.scheme_id);
  END IF;

  IF NEW.status = 'ASSIGNED' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM locations AS l
      JOIN scheme_levels AS sl
        ON sl.scheme_id = l.scheme_id
       AND sl.scheme_level_id = l.scheme_level_id
      WHERE l.scheme_id = NEW.scheme_id
        AND sl.is_search_terminal
    ) THEN
      RAISE EXCEPTION 'El esquema debe contener ubicaciones terminales de búsqueda';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM locations AS l
      JOIN scheme_levels AS sl
        ON sl.scheme_id = l.scheme_id
       AND sl.scheme_level_id = l.scheme_level_id
      WHERE l.scheme_id = NEW.scheme_id
        AND sl.is_search_terminal
        AND l.range_start_key IS NULL
    ) THEN
      RAISE EXCEPTION 'Todas las ubicaciones terminales deben tener un rango';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Aplica la máquina de estados al crear un esquema o cambiar su estado.
CREATE TRIGGER schemes_validate_state
BEFORE INSERT OR UPDATE OF status
ON schemes
FOR EACH ROW EXECUTE FUNCTION validate_scheme_state();

-- Permite editar capas solo después de cerrar la estructura de locations.
CREATE OR REPLACE FUNCTION ensure_map_layer_stage()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_scheme_id INTEGER;
  affected_status    scheme_status;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.scheme_id IS DISTINCT FROM NEW.scheme_id AND EXISTS (
    SELECT 1
    FROM schemes
    WHERE scheme_id IN (OLD.scheme_id, NEW.scheme_id)
      AND status NOT IN ('LOCATIONS_DEFINED', 'PARTIALLY_ASSIGNED', 'ASSIGNED')
  ) THEN
    RAISE EXCEPTION 'Los MapLayers solo pueden moverse entre esquemas con locations definidas';
  END IF;

  affected_scheme_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.scheme_id ELSE NEW.scheme_id END;

  SELECT status
  INTO affected_status
  FROM schemes
  WHERE scheme_id = affected_scheme_id;

  IF affected_status NOT IN ('LOCATIONS_DEFINED', 'PARTIALLY_ASSIGNED', 'ASSIGNED') THEN
    RAISE EXCEPTION 'Los MapLayers solo pueden configurarse después de definir las locations';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

-- Aplica la restricción de etapa a toda escritura de map_layers.
CREATE TRIGGER map_layers_require_locations_defined
BEFORE INSERT OR UPDATE OR DELETE
ON map_layers
FOR EACH ROW EXECUTE FUNCTION ensure_map_layer_stage();

-- Extiende la restricción de etapa a niveles, SVG y asignaciones de una capa.
CREATE OR REPLACE FUNCTION ensure_map_child_stage()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_map_layer_id INTEGER;
  affected_status       scheme_status;
BEGIN
  affected_map_layer_id := CASE
    WHEN TG_OP = 'DELETE' THEN OLD.map_layer_id
    ELSE NEW.map_layer_id
  END;

  SELECT s.status
  INTO affected_status
  FROM map_layers AS ml
  JOIN schemes AS s
    ON s.scheme_id = ml.scheme_id
  WHERE ml.map_layer_id = affected_map_layer_id;

  IF NOT FOUND AND TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  IF affected_status NOT IN ('LOCATIONS_DEFINED', 'PARTIALLY_ASSIGNED', 'ASSIGNED') THEN
    RAISE EXCEPTION 'La configuración de mapas requiere locations definidas';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

-- Restringe las asociaciones entre capas y niveles a las etapas permitidas.
CREATE TRIGGER map_layer_scheme_levels_require_locations_defined
BEFORE INSERT OR UPDATE OR DELETE
ON map_layer_scheme_levels
FOR EACH ROW EXECUTE FUNCTION ensure_map_child_stage();

-- Restringe la edición de SVG a las etapas permitidas.
CREATE TRIGGER map_layer_svgs_require_locations_defined
BEFORE INSERT OR UPDATE OR DELETE
ON map_layer_svgs
FOR EACH ROW EXECUTE FUNCTION ensure_map_child_stage();

-- Restringe la edición de asignaciones SVG a las etapas permitidas.
CREATE TRIGGER map_layer_svg_assignments_require_locations_defined
BEFORE INSERT OR UPDATE OR DELETE
ON map_layer_svg_assignments
FOR EACH ROW EXECUTE FUNCTION ensure_map_child_stage();

-- Mantiene en un esquema común la capa, el nivel representado y el drilldown.
CREATE OR REPLACE FUNCTION validate_map_layer_level()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  layer_scheme      INTEGER;
  level_scheme      INTEGER;
  drilldown_scheme  INTEGER;
  layer_mode        map_render_mode;
BEGIN
  SELECT scheme_id, render_mode
  INTO layer_scheme, layer_mode
  FROM map_layers
  WHERE map_layer_id = NEW.map_layer_id;

  SELECT scheme_id
  INTO level_scheme
  FROM scheme_levels
  WHERE scheme_level_id = NEW.scheme_level_id;

  IF layer_scheme IS DISTINCT FROM level_scheme THEN
    RAISE EXCEPTION 'El MapLayer y el nivel representado deben pertenecer al mismo esquema';
  END IF;

  IF NEW.drilldown_map_layer_id IS NOT NULL THEN
    SELECT scheme_id
    INTO drilldown_scheme
    FROM map_layers
    WHERE map_layer_id = NEW.drilldown_map_layer_id;

    IF layer_scheme IS DISTINCT FROM drilldown_scheme THEN
      RAISE EXCEPTION 'El MapLayer de drilldown debe pertenecer al mismo esquema';
    END IF;
  END IF;

  IF layer_mode = 'TEMPLATE' AND EXISTS (
    SELECT 1
    FROM map_layer_scheme_levels
    WHERE map_layer_id = NEW.map_layer_id
      AND scheme_level_id <> NEW.scheme_level_id
  ) THEN
    RAISE EXCEPTION 'Un MapLayer TEMPLATE solo puede representar un nivel en esta versión';
  END IF;

  RETURN NEW;
END;
$$;

-- Valida cada asociación de capa, nivel y destino de drilldown.
CREATE TRIGGER map_layer_scheme_levels_validate
BEFORE INSERT OR UPDATE
ON map_layer_scheme_levels
FOR EACH ROW EXECUTE FUNCTION validate_map_layer_level();

-- Impide cambiar el nivel representado mientras existan asignaciones SVG.
CREATE OR REPLACE FUNCTION protect_assigned_map_layer_level()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' AND NOT EXISTS (
    SELECT 1
    FROM map_layers
    WHERE map_layer_id = OLD.map_layer_id
  ) THEN
    RETURN OLD;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM map_layer_svg_assignments
    WHERE map_layer_id = OLD.map_layer_id
  ) THEN
    RAISE EXCEPTION 'Debe eliminar las asignaciones antes de cambiar el nivel representado';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

-- Protege las asociaciones asignadas frente a cambios de capa o nivel.
CREATE TRIGGER map_layer_scheme_levels_protect_update
BEFORE UPDATE OF map_layer_id, scheme_level_id
ON map_layer_scheme_levels
FOR EACH ROW EXECUTE FUNCTION protect_assigned_map_layer_level();

-- Protege las asociaciones asignadas frente a eliminación directa.
CREATE TRIGGER map_layer_scheme_levels_protect_delete
BEFORE DELETE
ON map_layer_scheme_levels
FOR EACH ROW EXECUTE FUNCTION protect_assigned_map_layer_level();

-- Comprueba que render_mode sea compatible con niveles, SVG y asignaciones existentes.
CREATE OR REPLACE FUNCTION validate_map_layer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.render_mode = 'TEMPLATE' AND (
    SELECT count(*)
    FROM map_layer_scheme_levels
    WHERE map_layer_id = NEW.map_layer_id
  ) > 1 THEN
    RAISE EXCEPTION 'Un MapLayer TEMPLATE solo puede representar un nivel en esta versión';
  END IF;

  IF NEW.render_mode = 'TEMPLATE' AND EXISTS (
    SELECT 1
    FROM map_layer_svgs
    WHERE map_layer_id = NEW.map_layer_id
      AND (variant_code IS NULL OR slot_count IS NULL)
  ) THEN
    RAISE EXCEPTION 'Los SVG existentes no son compatibles con el modo TEMPLATE';
  END IF;

  IF NEW.render_mode = 'STATIC' THEN
    IF EXISTS (
      SELECT 1
      FROM map_layer_svg_assignments
      WHERE map_layer_id = NEW.map_layer_id
    ) THEN
      RAISE EXCEPTION 'Un MapLayer STATIC no puede tener asignaciones de plantilla';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM map_layer_svgs
      WHERE map_layer_id = NEW.map_layer_id
        AND slot_count IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'Los SVG existentes no son compatibles con el modo STATIC';
    END IF;

    IF (
      SELECT count(*)
      FROM map_layer_svgs
      WHERE map_layer_id = NEW.map_layer_id
        AND enabled
    ) > 1 THEN
      RAISE EXCEPTION 'Un MapLayer STATIC solo puede tener un SVG habilitado';
    END IF;
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.scheme_id IS DISTINCT FROM OLD.scheme_id AND (
    EXISTS (
      SELECT 1
      FROM map_layer_scheme_levels AS mlsl
      JOIN scheme_levels AS sl
        ON sl.scheme_level_id = mlsl.scheme_level_id
      WHERE mlsl.map_layer_id = NEW.map_layer_id
        AND sl.scheme_id <> NEW.scheme_id
    )
    OR EXISTS (
      SELECT 1
      FROM map_layer_svg_assignments AS a
      JOIN locations AS l
        ON l.location_id = a.context_location_id
      WHERE a.map_layer_id = NEW.map_layer_id
        AND l.scheme_id <> NEW.scheme_id
    )
    OR EXISTS (
      SELECT 1
      FROM map_layer_scheme_levels AS mlsl
      JOIN map_layers AS source_layer
        ON source_layer.map_layer_id = mlsl.map_layer_id
      WHERE mlsl.drilldown_map_layer_id = NEW.map_layer_id
        AND source_layer.scheme_id <> NEW.scheme_id
    )
  ) THEN
    RAISE EXCEPTION 'No se puede cambiar el esquema del MapLayer mientras tenga relaciones incompatibles';
  END IF;

  RETURN NEW;
END;
$$;

-- Revalida relaciones y recursos cuando cambia el esquema o modo de una capa.
CREATE TRIGGER map_layers_validate
BEFORE UPDATE OF scheme_id, render_mode
ON map_layers
FOR EACH ROW EXECUTE FUNCTION validate_map_layer();

-- Exige metadatos compatibles con STATIC o TEMPLATE y protege plantillas asignadas.
CREATE OR REPLACE FUNCTION validate_map_layer_svg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  layer_mode map_render_mode;
BEGIN
  SELECT render_mode
  INTO layer_mode
  FROM map_layers
  WHERE map_layer_id = NEW.map_layer_id;

  IF layer_mode = 'STATIC' THEN
    IF NEW.slot_count IS NOT NULL THEN
      RAISE EXCEPTION 'Un SVG STATIC no utiliza slot_count';
    END IF;

    IF NEW.enabled AND EXISTS (
      SELECT 1
      FROM map_layer_svgs
      WHERE map_layer_id = NEW.map_layer_id
        AND enabled
        AND map_layer_svg_id <> NEW.map_layer_svg_id
    ) THEN
      RAISE EXCEPTION 'Un MapLayer STATIC solo puede tener un SVG habilitado';
    END IF;
  ELSE
    IF NEW.variant_code IS NULL OR NEW.slot_count IS NULL THEN
      RAISE EXCEPTION 'Un SVG TEMPLATE requiere variant_code y slot_count';
    END IF;
  END IF;

  IF TG_OP = 'UPDATE'
     AND EXISTS (
       SELECT 1
       FROM map_layer_svg_assignments
       WHERE map_layer_svg_id = OLD.map_layer_svg_id
     )
     AND (
       NEW.map_layer_id IS DISTINCT FROM OLD.map_layer_id
       OR NEW.slot_count IS DISTINCT FROM OLD.slot_count
       OR (OLD.enabled AND NOT NEW.enabled)
     )
  THEN
    RAISE EXCEPTION 'Debe eliminar las asignaciones antes de modificar o deshabilitar esta plantilla';
  END IF;

  RETURN NEW;
END;
$$;

-- Valida modo, variante, slots y habilitación al escribir un SVG.
CREATE TRIGGER map_layer_svgs_validate
BEFORE INSERT OR UPDATE OF map_layer_id, variant_code, slot_count, enabled
ON map_layer_svgs
FOR EACH ROW EXECUTE FUNCTION validate_map_layer_svg();

-- Comprueba esquema, nivel contextual, plantilla habilitada y cantidad de slots.
CREATE OR REPLACE FUNCTION validate_map_layer_svg_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  layer_scheme        INTEGER;
  layer_mode          map_render_mode;
  location_scheme     INTEGER;
  context_level_id    INTEGER;
  represented_level   INTEGER;
  expected_parent     INTEGER;
  expected_slots      INTEGER;
  actual_slots        INTEGER;
BEGIN
  SELECT scheme_id, render_mode
  INTO layer_scheme, layer_mode
  FROM map_layers
  WHERE map_layer_id = NEW.map_layer_id;

  IF layer_mode <> 'TEMPLATE' THEN
    RAISE EXCEPTION 'Solo los MapLayers TEMPLATE aceptan asignaciones';
  END IF;

  SELECT scheme_id, scheme_level_id
  INTO location_scheme, context_level_id
  FROM locations
  WHERE location_id = NEW.context_location_id;

  IF layer_scheme IS DISTINCT FROM location_scheme THEN
    RAISE EXCEPTION 'La ubicación contextual y el MapLayer deben pertenecer al mismo esquema';
  END IF;

  SELECT min(scheme_level_id), count(*)
  INTO represented_level, actual_slots
  FROM map_layer_scheme_levels
  WHERE map_layer_id = NEW.map_layer_id;

  IF actual_slots <> 1 THEN
    RAISE EXCEPTION 'El MapLayer TEMPLATE debe representar exactamente un nivel';
  END IF;

  SELECT parent_level_id
  INTO expected_parent
  FROM scheme_levels
  WHERE scheme_level_id = represented_level;

  IF expected_parent IS DISTINCT FROM context_level_id THEN
    RAISE EXCEPTION 'La ubicación contextual debe pertenecer al nivel padre del nivel representado';
  END IF;

  SELECT slot_count
  INTO expected_slots
  FROM map_layer_svgs
  WHERE map_layer_id = NEW.map_layer_id
    AND map_layer_svg_id = NEW.map_layer_svg_id
    AND enabled;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El SVG asignado no existe, no pertenece al MapLayer o está deshabilitado';
  END IF;

  SELECT count(*)
  INTO actual_slots
  FROM locations
  WHERE scheme_id = layer_scheme
    AND parent_location_id = NEW.context_location_id
    AND scheme_level_id = represented_level;

  IF actual_slots <> expected_slots THEN
    RAISE EXCEPTION
      'La plantilla requiere % slots, pero la ubicación tiene % elementos representables',
      expected_slots,
      actual_slots;
  END IF;

  RETURN NEW;
END;
$$;

-- Valida cada selección de plantilla para una ubicación contextual.
CREATE TRIGGER map_layer_svg_assignments_validate
BEFORE INSERT OR UPDATE
ON map_layer_svg_assignments
FOR EACH ROW EXECUTE FUNCTION validate_map_layer_svg_assignment();

-- Publica el esquema únicamente si todas las sentencias anteriores terminaron bien.
COMMIT;
