CREATE TYPE "scheme_status" AS ENUM (
  'DRAFT',
  'DEFINED',
  'DISTRIBUTED'
);

CREATE TYPE "structure_template_status" AS ENUM (
  'DRAFT',
  'ACTIVE',
  'ARCHIVED'
);

CREATE TYPE "process_status" AS ENUM (
  'PENDING',
  'DONE',
  'ERROR'
);

CREATE TYPE "location_role" AS ENUM (
  'CONTAINER',
  'POSITION'
);

CREATE TYPE "range_source" AS ENUM (
  'AUTO',
  'ANCHORED',
  'MANUAL'
);

CREATE TYPE "distribution_strategy" AS ENUM (
  'CAPACITY',
  'WEIGHTED',
  'ANCHORED',
  'HYBRID',
  'MANUAL'
);

CREATE TYPE "capacity_unit" AS ENUM (
  'BOOKS',
  'CENTIMETERS',
  'WEIGHT'
);

CREATE TYPE "load_error_severity" AS ENUM (
  'REVIEW',
  'REJECTED'
);

CREATE TYPE "user_role" AS ENUM (
  'ADMIN'
);

CREATE TABLE "users" (
  "user_id" SERIAL PRIMARY KEY,
  "username" VARCHAR(60) UNIQUE NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "full_name" VARCHAR(120),
  "role" user_role NOT NULL DEFAULT 'ADMIN',
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "last_login_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "schemes" (
  "scheme_id" SERIAL PRIMARY KEY,
  "name" VARCHAR(60) UNIQUE NOT NULL,
  "description" VARCHAR(255),
  "status" scheme_status NOT NULL DEFAULT 'DRAFT',
  "is_active" BOOLEAN NOT NULL DEFAULT false,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "based_on_scheme_id" INTEGER,
  "created_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_schemes_active_distributed"
    CHECK (NOT "is_active" OR "status" = 'DISTRIBUTED')
);

CREATE TABLE "structure_templates" (
  "structure_template_id" SERIAL PRIMARY KEY,
  "name" VARCHAR(60) UNIQUE NOT NULL,
  "description" VARCHAR(255),
  "status" structure_template_status NOT NULL DEFAULT 'DRAFT',
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "structure_template_nodes" (
  "structure_template_node_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "structure_template_id" INTEGER NOT NULL,
  "parent_template_node_id" INTEGER,
  "name" VARCHAR(40) NOT NULL,
  "role" location_role NOT NULL,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "visual_kind" VARCHAR(40),
  "default_capacity_value" NUMERIC(10, 2),
  "default_capacity_unit" capacity_unit,
  "default_target_fill_ratio" NUMERIC(5, 4),
  "default_allow_overflow" BOOLEAN,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_template_nodes_capacity_value"
    CHECK ("default_capacity_value" IS NULL OR "default_capacity_value" > 0),
  CONSTRAINT "ck_template_nodes_capacity_pair"
    CHECK (
      ("default_capacity_value" IS NULL) =
      ("default_capacity_unit" IS NULL)
    ),
  CONSTRAINT "ck_template_nodes_target_fill"
    CHECK (
      "default_target_fill_ratio" IS NULL
      OR (
        "default_target_fill_ratio" > 0
        AND "default_target_fill_ratio" <= 1
      )
    ),
  CONSTRAINT "ck_template_nodes_not_self"
    CHECK ("parent_template_node_id" <> "structure_template_node_id")
);

CREATE TABLE "locations" (
  "location_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scheme_id" INTEGER NOT NULL,
  "structure_template_id" INTEGER NOT NULL,
  "structure_template_node_id" INTEGER NOT NULL,
  "parent_location_id" INTEGER,
  "name" VARCHAR(60) NOT NULL,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "leaf_sequence" INTEGER,
  "map_element_id" VARCHAR(120),
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_locations_not_self"
    CHECK ("parent_location_id" <> "location_id"),
  CONSTRAINT "ck_locations_leaf_sequence"
    CHECK ("leaf_sequence" IS NULL OR "leaf_sequence" > 0)
);

CREATE TABLE "location_distribution_settings" (
  "location_distribution_setting_id" INTEGER
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" INTEGER NOT NULL,
  "scheme_id" INTEGER NOT NULL,
  "capacity_value" NUMERIC(10, 2),
  "capacity_unit" capacity_unit,
  "target_fill_ratio" NUMERIC(5, 4),
  "allow_overflow" BOOLEAN,
  "inherit_to_descendants" BOOLEAN NOT NULL DEFAULT false,
  "updated_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_location_settings_capacity_value"
    CHECK ("capacity_value" IS NULL OR "capacity_value" > 0),
  CONSTRAINT "ck_location_settings_capacity_pair"
    CHECK (("capacity_value" IS NULL) = ("capacity_unit" IS NULL)),
  CONSTRAINT "ck_location_settings_target_fill"
    CHECK (
      "target_fill_ratio" IS NULL
      OR (
        "target_fill_ratio" > 0
        AND "target_fill_ratio" <= 1
      )
    ),
  CONSTRAINT "ck_location_settings_has_value"
    CHECK (
      "capacity_value" IS NOT NULL
      OR "target_fill_ratio" IS NOT NULL
      OR "allow_overflow" IS NOT NULL
    )
);

CREATE TABLE "collection_loads" (
  "collection_load_id" SERIAL PRIMARY KEY,
  "title" VARCHAR(120) NOT NULL,
  "filename" VARCHAR(255) NOT NULL,
  "status" process_status NOT NULL DEFAULT 'PENDING',
  "rows_read" INTEGER NOT NULL DEFAULT 0,
  "rows_imported" INTEGER NOT NULL DEFAULT 0,
  "rows_without_key" INTEGER NOT NULL DEFAULT 0,
  "rows_flagged" INTEGER NOT NULL DEFAULT 0,
  "rows_rejected" INTEGER NOT NULL DEFAULT 0,
  "created_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_collection_load_counts" CHECK (
    "rows_read" >= 0
    AND "rows_imported" >= 0
    AND "rows_without_key" >= 0
    AND "rows_flagged" >= 0
    AND "rows_rejected" >= 0
  )
);

CREATE TABLE "collection_load_errors" (
  "collection_load_error_id" SERIAL PRIMARY KEY,
  "collection_load_id" INTEGER NOT NULL,
  "row_number" INTEGER NOT NULL,
  "severity" load_error_severity NOT NULL DEFAULT 'REVIEW',
  "reason" VARCHAR(255) NOT NULL,
  "raw_content" TEXT,
  CONSTRAINT "ck_collection_load_errors_row"
    CHECK ("row_number" > 0)
);

CREATE TABLE "books" (
  "book_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection_load_id" INTEGER NOT NULL,
  "source_row_number" INTEGER NOT NULL,
  "source_barcode" VARCHAR(20) NOT NULL,
  "classification_raw" VARCHAR(60),
  "comparable_key" VARCHAR(60) COLLATE "C",
  "isbn" VARCHAR(60),
  "title" VARCHAR(255),
  "author" VARCHAR(255),
  "copy_label" VARCHAR(20),
  "year" SMALLINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_books_year"
    CHECK ("year" IS NULL OR "year" BETWEEN 1400 AND 2200),
  CONSTRAINT "ck_books_source_row"
    CHECK ("source_row_number" > 0),
  CONSTRAINT "ck_books_key_below_sentinel"
    CHECK ("comparable_key" IS NULL OR "comparable_key" < '~')
);

CREATE TABLE "distribution_runs" (
  "distribution_run_id" SERIAL PRIMARY KEY,
  "scheme_id" INTEGER NOT NULL,
  "collection_load_id" INTEGER NOT NULL,
  "based_on_distribution_run_id" INTEGER,
  "strategy" distribution_strategy NOT NULL DEFAULT 'HYBRID',
  "parameters" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "status" process_status NOT NULL DEFAULT 'PENDING',
  "default_capacity_value" NUMERIC(10, 2),
  "default_capacity_unit" capacity_unit,
  "default_target_fill_ratio" NUMERIC(5, 4) NOT NULL DEFAULT 1,
  "default_allow_overflow" BOOLEAN NOT NULL DEFAULT true,
  "book_count" INTEGER NOT NULL DEFAULT 0,
  "position_count" INTEGER NOT NULL DEFAULT 0,
  "unassigned_count" INTEGER NOT NULL DEFAULT 0,
  "is_published" BOOLEAN NOT NULL DEFAULT false,
  "published_at" TIMESTAMPTZ,
  "error_message" TEXT,
  "created_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "finished_at" TIMESTAMPTZ,
  CONSTRAINT "ck_distribution_default_capacity_value"
    CHECK (
      "default_capacity_value" IS NULL
      OR "default_capacity_value" > 0
    ),
  CONSTRAINT "ck_distribution_default_capacity_pair"
    CHECK (
      ("default_capacity_value" IS NULL) =
      ("default_capacity_unit" IS NULL)
    ),
  CONSTRAINT "ck_distribution_default_target_fill"
    CHECK (
      "default_target_fill_ratio" > 0
      AND "default_target_fill_ratio" <= 1
    ),
  CONSTRAINT "ck_distribution_counts"
    CHECK (
      "book_count" >= 0
      AND "position_count" >= 0
      AND "unassigned_count" >= 0
    ),
  CONSTRAINT "ck_distribution_published"
    CHECK (
      NOT "is_published"
      OR (
        "status" = 'DONE'
        AND "published_at" IS NOT NULL
      )
    )
);

CREATE TABLE "distribution_position_inputs" (
  "distribution_position_input_id" INTEGER
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "distribution_run_id" INTEGER NOT NULL,
  "scheme_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "position_sequence" INTEGER NOT NULL,
  "capacity_value" NUMERIC(10, 2),
  "capacity_unit" capacity_unit,
  "target_fill_ratio" NUMERIC(5, 4) NOT NULL,
  "allow_overflow" BOOLEAN NOT NULL,
  "resolution" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_distribution_position_sequence"
    CHECK ("position_sequence" > 0),
  CONSTRAINT "ck_distribution_position_capacity_value"
    CHECK ("capacity_value" IS NULL OR "capacity_value" > 0),
  CONSTRAINT "ck_distribution_position_capacity_pair"
    CHECK (("capacity_value" IS NULL) = ("capacity_unit" IS NULL)),
  CONSTRAINT "ck_distribution_position_target_fill"
    CHECK ("target_fill_ratio" > 0 AND "target_fill_ratio" <= 1)
);

CREATE TABLE "distribution_anchors" (
  "distribution_anchor_id" INTEGER
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "distribution_run_id" INTEGER NOT NULL,
  "scheme_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "boundary_key" VARCHAR(60) COLLATE "C" NOT NULL,
  "boundary_code" VARCHAR(60) NOT NULL,
  "created_by" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_distribution_anchor_boundary"
    CHECK ("boundary_key" > '' AND "boundary_key" < '~')
);

CREATE TABLE "distribution_ranges" (
  "distribution_range_id" INTEGER
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "distribution_run_id" INTEGER NOT NULL,
  "scheme_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "range_sequence" INTEGER NOT NULL,
  "range_start_key" VARCHAR(60) COLLATE "C" NOT NULL,
  "range_end_key" VARCHAR(60) COLLATE "C" NOT NULL,
  "range_start_code" VARCHAR(60),
  "range_end_code" VARCHAR(60),
  "source" range_source NOT NULL DEFAULT 'AUTO',
  "book_count" INTEGER NOT NULL DEFAULT 0,
  "reviewed_by" INTEGER,
  "reviewed_at" TIMESTAMPTZ,
  "review_notes" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "ck_distribution_ranges_sequence"
    CHECK ("range_sequence" > 0),
  CONSTRAINT "ck_distribution_ranges_order"
    CHECK ("range_start_key" < "range_end_key"),
  CONSTRAINT "ck_distribution_ranges_book_count"
    CHECK ("book_count" >= 0),
  CONSTRAINT "ck_distribution_ranges_sentinel"
    CHECK ("range_end_key" <= '~')
);

CREATE TABLE "book_placements" (
  "book_placement_id" INTEGER
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "distribution_run_id" INTEGER NOT NULL,
  "scheme_id" INTEGER NOT NULL,
  "collection_load_id" INTEGER NOT NULL,
  "book_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "source" range_source NOT NULL DEFAULT 'AUTO',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "uq_schemes_one_active"
ON "schemes" ("is_active")
WHERE "is_active";

CREATE UNIQUE INDEX "uq_template_nodes_id_template"
ON "structure_template_nodes" (
  "structure_template_node_id",
  "structure_template_id"
);

CREATE UNIQUE INDEX "uq_template_nodes_one_root"
ON "structure_template_nodes" ("structure_template_id")
WHERE "parent_template_node_id" IS NULL;

CREATE UNIQUE INDEX "uq_template_nodes_sibling_name"
ON "structure_template_nodes" (
  "parent_template_node_id",
  "name"
)
WHERE "parent_template_node_id" IS NOT NULL;

CREATE UNIQUE INDEX "uq_template_nodes_sibling_order"
ON "structure_template_nodes" (
  "parent_template_node_id",
  "sort_order"
)
WHERE "parent_template_node_id" IS NOT NULL;

CREATE UNIQUE INDEX "uq_locations_id_scheme"
ON "locations" ("location_id", "scheme_id");

CREATE UNIQUE INDEX "uq_locations_id_instance"
ON "locations" (
  "location_id",
  "scheme_id",
  "structure_template_id"
);

CREATE UNIQUE INDEX "uq_locations_sibling_name"
ON "locations" ("parent_location_id", "name")
WHERE "parent_location_id" IS NOT NULL;

CREATE UNIQUE INDEX "uq_locations_sibling_order"
ON "locations" ("parent_location_id", "sort_order")
WHERE "parent_location_id" IS NOT NULL;

CREATE UNIQUE INDEX "uq_locations_root_name"
ON "locations" ("scheme_id", "name")
WHERE "parent_location_id" IS NULL;

CREATE UNIQUE INDEX "uq_locations_root_order"
ON "locations" ("scheme_id", "sort_order")
WHERE "parent_location_id" IS NULL;

CREATE UNIQUE INDEX "uq_locations_map_element"
ON "locations" ("scheme_id", "map_element_id");

CREATE UNIQUE INDEX "uq_locations_leaf_sequence"
ON "locations" ("scheme_id", "leaf_sequence")
WHERE "leaf_sequence" IS NOT NULL;

CREATE INDEX "ix_locations_tree"
ON "locations" ("parent_location_id", "sort_order");

CREATE INDEX "ix_locations_scheme"
ON "locations" ("scheme_id");

CREATE INDEX "ix_locations_sequence"
ON "locations" ("scheme_id", "leaf_sequence");

CREATE UNIQUE INDEX "uq_location_settings_location"
ON "location_distribution_settings" ("location_id");

CREATE UNIQUE INDEX "uq_books_id_load"
ON "books" ("book_id", "collection_load_id");

CREATE UNIQUE INDEX "uq_books_load_row"
ON "books" ("collection_load_id", "source_row_number");

CREATE INDEX "ix_books_barcode"
ON "books" ("collection_load_id", "source_barcode");

CREATE INDEX "ix_books_key"
ON "books" ("comparable_key");

CREATE INDEX "ix_books_load"
ON "books" ("collection_load_id", "comparable_key");

CREATE UNIQUE INDEX "uq_distribution_runs_id_scheme"
ON "distribution_runs" ("distribution_run_id", "scheme_id");

CREATE UNIQUE INDEX "uq_distribution_runs_id_load"
ON "distribution_runs" (
  "distribution_run_id",
  "collection_load_id"
);

CREATE UNIQUE INDEX "uq_distribution_runs_one_published"
ON "distribution_runs" ("scheme_id")
WHERE "is_published";

CREATE INDEX "ix_distribution_runs_scheme"
ON "distribution_runs" ("scheme_id", "created_at");

CREATE UNIQUE INDEX "uq_distribution_positions_run_location"
ON "distribution_position_inputs" (
  "distribution_run_id",
  "scheme_id",
  "location_id"
);

CREATE UNIQUE INDEX "uq_distribution_positions_sequence"
ON "distribution_position_inputs" (
  "distribution_run_id",
  "position_sequence"
);

CREATE UNIQUE INDEX "uq_distribution_anchors_run_location"
ON "distribution_anchors" (
  "distribution_run_id",
  "location_id"
);

CREATE INDEX "ix_distribution_anchors_key"
ON "distribution_anchors" (
  "distribution_run_id",
  "boundary_key"
);

CREATE UNIQUE INDEX "uq_distribution_ranges_sequence"
ON "distribution_ranges" (
  "distribution_run_id",
  "range_sequence"
);

CREATE INDEX "ix_distribution_ranges_lookup"
ON "distribution_ranges" (
  "distribution_run_id",
  "range_start_key",
  "range_end_key"
);

CREATE INDEX "ix_distribution_ranges_location"
ON "distribution_ranges" (
  "distribution_run_id",
  "location_id"
);

CREATE UNIQUE INDEX "uq_book_placements_run_book"
ON "book_placements" ("distribution_run_id", "book_id");

CREATE INDEX "ix_book_placements_location"
ON "book_placements" (
  "distribution_run_id",
  "location_id"
);

COMMENT ON TABLE "structure_templates" IS
  'Reusable hierarchy definitions. Cardinalities live in concrete locations.';

COMMENT ON COLUMN "structure_template_nodes"."role" IS
  'CONTAINER groups locations; POSITION receives distribution.';

COMMENT ON COLUMN "locations"."sort_order" IS
  'Order among siblings. Root locations are ordered within their scheme.';

COMMENT ON COLUMN "locations"."leaf_sequence" IS
  'Derived global order of POSITION locations within a scheme.';

COMMENT ON COLUMN "location_distribution_settings"."inherit_to_descendants" IS
  'If true, non-null values act as defaults for descendant POSITION locations.';

COMMENT ON TABLE "distribution_position_inputs" IS
  'Snapshot of ordered positions and resolved settings used by one run.';

COMMENT ON TABLE "distribution_anchors" IS
  'Manual input: the associated POSITION starts at boundary_key.';

COMMENT ON COLUMN "distribution_ranges"."range_end_key" IS
  'Exclusive upper bound.';

COMMENT ON TABLE "book_placements" IS
  'Algorithmic per-record assignments. Public locations remain approximate.';

ALTER TABLE "schemes"
ADD CONSTRAINT "fk_schemes_based_on"
FOREIGN KEY ("based_on_scheme_id")
REFERENCES "schemes" ("scheme_id")
ON DELETE SET NULL
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "schemes"
ADD CONSTRAINT "fk_schemes_creator"
FOREIGN KEY ("created_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "structure_templates"
ADD CONSTRAINT "fk_structure_templates_creator"
FOREIGN KEY ("created_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "structure_template_nodes"
ADD CONSTRAINT "fk_template_nodes_template"
FOREIGN KEY ("structure_template_id")
REFERENCES "structure_templates" ("structure_template_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "structure_template_nodes"
ADD CONSTRAINT "fk_template_nodes_parent"
FOREIGN KEY (
  "parent_template_node_id",
  "structure_template_id"
)
REFERENCES "structure_template_nodes" (
  "structure_template_node_id",
  "structure_template_id"
)
ON DELETE RESTRICT
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "locations"
ADD CONSTRAINT "fk_locations_scheme"
FOREIGN KEY ("scheme_id")
REFERENCES "schemes" ("scheme_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "locations"
ADD CONSTRAINT "fk_locations_template_node"
FOREIGN KEY (
  "structure_template_node_id",
  "structure_template_id"
)
REFERENCES "structure_template_nodes" (
  "structure_template_node_id",
  "structure_template_id"
)
ON DELETE RESTRICT
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "locations"
ADD CONSTRAINT "fk_locations_parent"
FOREIGN KEY (
  "parent_location_id",
  "scheme_id",
  "structure_template_id"
)
REFERENCES "locations" (
  "location_id",
  "scheme_id",
  "structure_template_id"
)
ON DELETE RESTRICT
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_distribution_settings"
ADD CONSTRAINT "fk_location_settings_location"
FOREIGN KEY ("location_id", "scheme_id")
REFERENCES "locations" ("location_id", "scheme_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_distribution_settings"
ADD CONSTRAINT "fk_location_settings_user"
FOREIGN KEY ("updated_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "collection_loads"
ADD CONSTRAINT "fk_collection_loads_creator"
FOREIGN KEY ("created_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "collection_load_errors"
ADD CONSTRAINT "fk_collection_load_errors_load"
FOREIGN KEY ("collection_load_id")
REFERENCES "collection_loads" ("collection_load_id")
ON DELETE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "books"
ADD CONSTRAINT "fk_books_load"
FOREIGN KEY ("collection_load_id")
REFERENCES "collection_loads" ("collection_load_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_runs"
ADD CONSTRAINT "fk_distribution_runs_scheme"
FOREIGN KEY ("scheme_id")
REFERENCES "schemes" ("scheme_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_runs"
ADD CONSTRAINT "fk_distribution_runs_load"
FOREIGN KEY ("collection_load_id")
REFERENCES "collection_loads" ("collection_load_id")
ON DELETE RESTRICT
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_runs"
ADD CONSTRAINT "fk_distribution_runs_based_on"
FOREIGN KEY (
  "based_on_distribution_run_id",
  "scheme_id"
)
REFERENCES "distribution_runs" (
  "distribution_run_id",
  "scheme_id"
)
ON DELETE SET NULL ("based_on_distribution_run_id")
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_runs"
ADD CONSTRAINT "fk_distribution_runs_creator"
FOREIGN KEY ("created_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_position_inputs"
ADD CONSTRAINT "fk_distribution_positions_run"
FOREIGN KEY ("distribution_run_id", "scheme_id")
REFERENCES "distribution_runs" (
  "distribution_run_id",
  "scheme_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_position_inputs"
ADD CONSTRAINT "fk_distribution_positions_location"
FOREIGN KEY ("location_id", "scheme_id")
REFERENCES "locations" ("location_id", "scheme_id")
ON DELETE RESTRICT
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_anchors"
ADD CONSTRAINT "fk_distribution_anchors_position"
FOREIGN KEY (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
REFERENCES "distribution_position_inputs" (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_anchors"
ADD CONSTRAINT "fk_distribution_anchors_creator"
FOREIGN KEY ("created_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_ranges"
ADD CONSTRAINT "fk_distribution_ranges_position"
FOREIGN KEY (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
REFERENCES "distribution_position_inputs" (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "distribution_ranges"
ADD CONSTRAINT "fk_distribution_ranges_reviewer"
FOREIGN KEY ("reviewed_by")
REFERENCES "users" ("user_id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_placements"
ADD CONSTRAINT "fk_book_placements_run_scheme"
FOREIGN KEY ("distribution_run_id", "scheme_id")
REFERENCES "distribution_runs" (
  "distribution_run_id",
  "scheme_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_placements"
ADD CONSTRAINT "fk_book_placements_run_load"
FOREIGN KEY (
  "distribution_run_id",
  "collection_load_id"
)
REFERENCES "distribution_runs" (
  "distribution_run_id",
  "collection_load_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_placements"
ADD CONSTRAINT "fk_book_placements_book"
FOREIGN KEY ("book_id", "collection_load_id")
REFERENCES "books" ("book_id", "collection_load_id")
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_placements"
ADD CONSTRAINT "fk_book_placements_position"
FOREIGN KEY (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
REFERENCES "distribution_position_inputs" (
  "distribution_run_id",
  "scheme_id",
  "location_id"
)
ON DELETE CASCADE
ON UPDATE CASCADE
DEFERRABLE INITIALLY IMMEDIATE;
